name: "clairs"
description: ClairS is a deep-learning-based method for calling somatic variants from paired tumor-normal long-read sequencing data.
keywords:
  - somatic
  - variant
  - cancer
  - SNV
tools:
  - "clairs":
      description: "ClairS - a deep-learning method for somatic variant calling using paired tumor-normal long-reads"
      homepage: "https://github.com/HKU-BAL/ClairS"
      documentation: "https://github.com/HKU-BAL/ClairS"
      tool_dev_url: "https://github.com/HKU-BAL/ClairS"
      licence:
        - "BSD-3-clause"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - tumor_bam:
        type: file
        description: Sorted BAM file of tumor sample
        pattern: "*.{bam}"
    - tumor_bai:
        type: file
        description: BAM index file of tumor sample
        pattern: "*.bai"
    - normal_bam:
        type: file
        description: Sorted BAM file of normal sample
        pattern: "*.{bam}"
    - normal_bai:
        type: file
        description: BAM index file of normal sample
        pattern: "*.bai"
    - platform:
        type: string
        description: sequencing platform/model configuration (e.g. 'ont_r10_dorado_sup_4khz', 'hifi_revio')
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reference:
        type: file
        description: reference fasta file
        pattern: "*.fasta"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reference_index:
        type: file
        description: reference index file
        pattern: "*.fai"
output:
  - vcf:
      type: file
      description: Somatic VCF file containing called variants
      pattern: "*.vcf.gz"
  - tbi:
      type: file
      description: Index for somatic VCF file
      pattern: "*.vcf.gz.tbi"
  - versions:
      type: file
      description: File containing version information
      pattern: "versions.yml"
authors:
  - "@HKU-BAL"
