name: epinano_variants
description: EpiNano is a tool to identify RNA modifications present in direct RNA sequencing reads.
keywords:
  - epinano
  - RNA
tools:
  - epinano:
      description: |
        EpiNano is a tool to identify RNA modifications present in direct RNA sequencing reads. EpiNano will extract a set of 'features' from direct RNA sequencing reads, which will be in turn used to predict whether the 'error' is caused by the presence of an RNA modification or not.
      documentation: https://github.com/novoalab/EpiNano
      licence: ["GPL-2.0"]
      homepage: https://github.com/novoalab/EpiNano
      doi: doi.org/10.1016/j.gpb.2023.02.002

authors:
  - "@lucacozzuto"
maintainers:
  - "@lucacozzuto"
