name: cellranger_multi
description: Module to use Cell Ranger's pipelines analyze sequencing data produced
  from Chromium Single Cell Gene Expression.
keywords:
  - align
  - count
  - reference
tools:
  - cellranger:
      description: Cell Ranger by 10x Genomics is a set of analysis pipelines that process
        Chromium single-cell data to align reads, generate feature-barcode matrices,
        perform clustering and other secondary analysis, and more.
      homepage: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger
      documentation: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ov
      tool_dev_url: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ov
      licence:
        - 10x Genomics EULA
      identifier: ""
