name: nanorms_baseq
description: NanoRMS: predicting NANOpore Rna Modification Stoichiometry
keywords:
  - baseq
  - RNA
tools:
  - nanorms:
      description: |
        NanoRMS predicts modification stoichiometries by classifying reads into modified/unmodified, based on their per-read features (current intensity, dwell time and/or trace).
      documentation: https://github.com/novoalab/nanoRMS
      licence: ["GPL-2.0"]
      homepage: https://github.com/novoalab/nanoRMS
      doi: https://doi.org/10.1038/s41587-021-00915-6

authors:
  - "@lucacozzuto"
maintainers:
  - "@lucacozzuto"
