name: nanoconsensus
description: "NanoConsensus: consensus prediction of RNA modifications from direct RNA nanopore sequencing data"
keywords:
  - nanoconsensus
  - RNA
tools:
  - nanorms:
      description: |
        NanoConsensus is an software to robustly identify putative RNA modified sites from direct RNA sequencing datasets.
      documentation: https://github.com/novoalab/NanoConsensus/blob/master/README.md
      licence: ["MIT"]
      homepage: https://github.com/novoalab/NanoConsensus/
      doi: https://doi.org/10.1038/s41467-025-55846-6

authors:
  - "@lucacozzuto"
maintainers:
  - "@lucacozzuto"